export const plans = [
  {
    id: 1,
    names: "Samir Slim",
    price_month: 2,
    price_annual: 20,
    electronic_documents: 7000,
    users: 40,
    business: 10,
    active_plan: true,
    features: [
      "Módulo de Notas de Crédito",
      "Módulo de Notas de Débito",
      "Módulo de Ventas",
      "Módulo de Guías de Remisión",
      "Exportar Documentos (XLS, XML, PDF)",
      "Módulo de Inventarios",
      "Módulo de Tesorería",
    ],
  },
  {
    id: 2,
    names: "Samir Plus",
    price_month: 3,
    price_annual: 24,
    electronic_documents: 7000,
    users: 40,
    business: 10,
    active_plan: false,
    features: [
      "Módulo de Notas de Crédito",
      "Módulo de Notas de Débito",
      "Módulo de Ventas",
      "Módulo de Guías de Remisión",
      "Exportar Documentos (XLS, XML, PDF)",
      "Módulo de Inventarios",
      "Módulo de Tesorería",
    ],
  },
  {
    id: 3,
    names: "Samir Ultra",
    price_month: 4,
    price_annual: 28,
    electronic_documents: 7000,
    users: 40,
    business: 10,
    active_plan: false,
    features: [
      "Módulo de Notas de Crédito",
      "Módulo de Notas de Débito",
      "Módulo de Ventas",
      "Módulo de Guías de Remisión",
      "Exportar Documentos (XLS, XML, PDF)",
      "Módulo de Inventarios",
      "Módulo de Tesorería",
    ],
  },
];
